version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cybersec_advisory
      POSTGRES_USER: cybersec_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://cybersec_user:${POSTGRES_PASSWORD}@postgres:5432/cybersec_advisory
